[project]
name = "rustoracerpy-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["rustoracerpy>=0.1.11", "stable-baselines3>=2.7.1"]
